import { InstalledApp } from '../types';

export const DEFAULT_INSTALLED_APPS: InstalledApp[] = [
  // Built-in mini activities
  {
    id: 'drawing',
    name: 'Kids Art Studio',
    category: 'creative',
    iconEmoji: '🎨',
    colorGradient: 'from-pink-500 to-rose-600',
    description: 'Paint, sketch, and doodle with fun vibrant colors',
    enabled: true,
    isBuiltIn: true,
    ageRating: 'All Ages',
  },
  {
    id: 'math',
    name: 'Math Galaxy',
    category: 'education',
    iconEmoji: '🚀',
    colorGradient: 'from-cyan-500 to-blue-600',
    description: 'Fun space math puzzles and star rewards',
    enabled: true,
    isBuiltIn: true,
    ageRating: 'Ages 5+',
  },
  {
    id: 'storybook',
    name: 'Storybook Adventure',
    category: 'books',
    iconEmoji: '📚',
    colorGradient: 'from-amber-500 to-orange-600',
    description: 'Animated stories with read-aloud voice',
    enabled: true,
    isBuiltIn: true,
    ageRating: 'All Ages',
  },
  {
    id: 'tunes',
    name: 'Rainbow Piano',
    category: 'creative',
    iconEmoji: '🎵',
    colorGradient: 'from-purple-500 to-indigo-600',
    description: 'Play melodies on colorful synthesizer keys',
    enabled: true,
    isBuiltIn: true,
    ageRating: 'All Ages',
  },

  // Popular Device-Installed Games & Educational Apps
  {
    id: 'minecraft',
    name: 'Minecraft: Pocket Edition',
    category: 'games',
    packageName: 'com.mojang.minecraftpe',
    iconEmoji: '⛏️',
    colorGradient: 'from-emerald-600 to-green-800',
    description: 'Build creative worlds, mine resources, and craft structures',
    enabled: true,
    isBuiltIn: false,
    ageRating: 'Ages 7+',
  },
  {
    id: 'youtube_kids',
    name: 'YouTube Kids',
    category: 'media',
    packageName: 'com.google.android.apps.youtube.kids',
    iconEmoji: '▶️',
    colorGradient: 'from-red-500 to-rose-700',
    description: 'Curated kid-safe cartoons, science videos, and learning clips',
    enabled: true,
    isBuiltIn: false,
    ageRating: 'All Ages',
  },
  {
    id: 'duolingo_kids',
    name: 'Duolingo ABC: Learn to Read',
    category: 'education',
    packageName: 'com.duolingo.kids',
    iconEmoji: '🦉',
    colorGradient: 'from-green-500 to-emerald-600',
    description: 'Fun interactive phonics, tracing, and reading games',
    enabled: true,
    isBuiltIn: false,
    ageRating: 'Ages 3+',
  },
  {
    id: 'pbs_kids',
    name: 'PBS KIDS Games',
    category: 'games',
    packageName: 'org.pbskids.games',
    iconEmoji: '🐯',
    colorGradient: 'from-amber-500 to-yellow-600',
    description: 'Over 200 fun educational games featuring favorite characters',
    enabled: true,
    isBuiltIn: false,
    ageRating: 'Ages 4+',
  },
  {
    id: 'scratch_jr',
    name: 'ScratchJr Coding',
    category: 'creative',
    packageName: 'org.scratchjr.android',
    iconEmoji: '🐱',
    colorGradient: 'from-orange-500 to-amber-600',
    description: 'Introductory visual coding blocks for young children',
    enabled: false,
    isBuiltIn: false,
    ageRating: 'Ages 5+',
  },
  {
    id: 'chess_kids',
    name: 'Chess for Kids',
    category: 'games',
    packageName: 'com.chess.kids',
    iconEmoji: '♟️',
    colorGradient: 'from-slate-700 to-slate-900',
    description: 'Learn chess tactics with animated puzzles and friendly bots',
    enabled: false,
    isBuiltIn: false,
    ageRating: 'Ages 6+',
  },
  {
    id: 'roblox_kids',
    name: 'Roblox Kids Sandbox',
    category: 'games',
    packageName: 'com.roblox.client',
    iconEmoji: '🧱',
    colorGradient: 'from-blue-600 to-indigo-800',
    description: 'Parent-supervised 3D mini-games and obbies',
    enabled: false,
    isBuiltIn: false,
    ageRating: 'Ages 9+',
  },
  {
    id: 'toca_life',
    name: 'Toca Life World',
    category: 'games',
    packageName: 'com.tocaboca.tocalifeworld',
    iconEmoji: '🏰',
    colorGradient: 'from-fuchsia-500 to-pink-600',
    description: 'Create characters, build houses, and tell stories in a mega world',
    enabled: false,
    isBuiltIn: false,
    ageRating: 'Ages 6+',
  },
];

// Catalog of quick-add popular apps/games installed on Android tablets
export const POPULAR_CATALOG_SUGGESTIONS: Omit<InstalledApp, 'enabled'>[] = [
  {
    id: 'subway_surfers',
    name: 'Subway Surfers',
    category: 'games',
    packageName: 'com.kiloo.subwaysurf',
    iconEmoji: '🛹',
    colorGradient: 'from-teal-500 to-emerald-600',
    description: 'Endless running game dodging trains and collecting gold coins',
    isBuiltIn: false,
    ageRating: 'Ages 9+',
  },
  {
    id: 'khan_kids',
    name: 'Khan Academy Kids',
    category: 'education',
    packageName: 'org.khankids.android',
    iconEmoji: '🐻',
    colorGradient: 'from-teal-600 to-cyan-700',
    description: 'Free comprehensive early learning program with math and logic',
    isBuiltIn: false,
    ageRating: 'Ages 2-8',
  },
  {
    id: 'lego_duplo',
    name: 'LEGO DUPLO World',
    category: 'games',
    packageName: 'com.storytoys.legoduplo.free.android',
    iconEmoji: '🧩',
    colorGradient: 'from-red-600 to-yellow-500',
    description: '3D building fun with interactive animals, trains, and vehicles',
    isBuiltIn: false,
    ageRating: 'Ages 2-5',
  },
  {
    id: 'crossy_road',
    name: 'Crossy Road',
    category: 'games',
    packageName: 'com.yodo1.crossyroad',
    iconEmoji: '🐔',
    colorGradient: 'from-lime-500 to-green-600',
    description: 'Endless arcade hopper crossing busy roads and train tracks',
    isBuiltIn: false,
    ageRating: 'Ages 6+',
  },
  {
    id: 'epic_books',
    name: 'Epic: Kids Books & Audio',
    category: 'books',
    packageName: 'com.getepic.Epic',
    iconEmoji: '📖',
    colorGradient: 'from-blue-500 to-cyan-600',
    description: 'Digital reading library of 40,000+ kid-safe picture books',
    isBuiltIn: false,
    ageRating: 'All Ages',
  },
  {
    id: 'fruit_ninja',
    name: 'Fruit Ninja Classic',
    category: 'games',
    packageName: 'com.halfbrick.fruitninjafree',
    iconEmoji: '🍉',
    colorGradient: 'from-emerald-500 to-orange-500',
    description: 'Slice flying fruits with swipe gestures and combos',
    isBuiltIn: false,
    ageRating: 'Ages 6+',
  },
];
